[package]
name = "slippage_check"
edition = "2024.beta"
published-at = "0xfd6a45c396a90811fd93efaf585cc95c29aecd079c87822893f1e97e3fee8c50"

[dependencies]
Sui = { git = "https://github.com/MystenLabs/sui.git", subdir = "crates/sui-framework/packages/sui-framework", rev = "framework/testnet", override = true }


[addresses]
slippage_check = "0xfd6a45c396a90811fd93efaf585cc95c29aecd079c87822893f1e97e3fee8c50"

